export const optionsSelect = [
    { value: "Brasileira", label: "Brasileira" },
    { value: "Mexicana", label: "Mexicana" },
    { value: "Japonesa", label: "Japonesa" },
    { value: "Americana", label: "Americana" },
    { value: "Italiana", label: "Italiana" },
    { value: "Lanches", label: "Lanches" },
    { value: "Pizza", label: "Pizza" },
    { value: "Churrasco", label: "Churrasco" },
    { value: "Saudavel", label: "Saudável" },
    { value: "Bebidas", label: "Bebidas" },
    { value: "Acai", label: "Açaí" },
    { value: "Petiscos", label: "Petiscos" },
    { value: "Chinesa", label: "Chinesa" },
    { value: "Sobremesas", label: "Sobremesas" },
]